name: Build, Push and Deploy Docker Image

on:
    push:             # Trigger this workflow on every push to the main branch
        branches:
            - main    # The branch on which this workflows applies

jobs:
    build:
        # The environment in which this job runs
        runs-on: ubuntu-latest


        steps:
            # Step 1: Checkout the repo
            - name: Checkout repository
              uses: actions/checkout@v2

            
            # Step 2: Logging in to Docker Hub using secrets for security reasons
            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


            # Step 3: Build the docker image using the Dockerfile present in Group_3/api directory
            - name: Build the Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/supabase-fastapi-endpoints:latest -f Group_3/api/Dockerfile .


            # Step 4: Push the docker image to docker hub
            - name: Push the Docker Image to Docker Hub
              run: docker push ${{ secrets.DOCKER_USERNAME }}/supabase-fastapi-endpoints:latest

            
            # Step 5: Trigger Render Deploy Hook to redeploy the Docker Image
            - name: Trigger Render Deploy Hook
              run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}" -d ''